api: "== 0.6.*"

# default vars
vars: {}

run:
# script ENV var $VARS point to temporary json file with current context vars
- script: |
    echo "
    Usage:
      stack template clusters.[CLUSTER] -t [TAGS] -f vars.yaml
      or
      stack template -t [CLUSTER] [TAGS] -f vars.yaml
    " 1>&2

stacks:
- clusters.dev

tags:
- dev

logs: color
